name: check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js LTS
        uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: lts/*

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build

      - name: Lint
        run: pnpm run lint

      - name: Type Check
        run: pnpm run check-types

      - name: Test
        run: pnpm run test
